#!/usr/bin/env bash
# A Bash script that displays "To infinity and beyond" indefinitely and handles SIGTERM gracefully

# Trap SIGTERM and print custom message instead of terminating
trap 'echo "I am invincible!!!"' SIGTERM

# Infinite loop
while true
do
    echo "To infinity and beyond"
    sleep 2
done
